--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/EnderVault
build-by-default: true
branches:
- main
projects:
  EnderVault:
    path: ""
    lint: false
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.5
...
